### ISSUE TITLE
Twitter API changes

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/getting-started-with-the-twitter-api#12]
We should review this project as the twitter API and development requirements have changed.

https://blog.twitter.com/developer/en_us/topics/tools/2018/new-developer-requirements-to-protect-our-platform.html

At a minimum it looks like the registration process has changed significantly.

**Comment by martinohanlon** [comment]
Applied for twitter developer account (and took all the screenshots), awaiting for approval before I can continue.

**Comment by andypiper** [comment]
@martinohanlon I followed you on Twitter, DM me with details and and I can see if I can help.

**Comment by martinohanlon** [comment]
Received notification that my twitter developer account has been approved.

**Comment by martinohanlon** [comment]
Made changes in draft and sent for copy edit.

**Comment by martinohanlon** [comment]
Resolved with #14
