### ISSUE TITLE
Twitter & Phone number

### ISSUE THREAD

**Issue by bsimmo** [raspberrypilearning/getting-started-with-the-twitter-api#4]
This may be an issue for Educators using Twitter,
and account requires a phone number if creating an application.

> Error
> You must add your mobile phone to your Twitter profile before creating an application. Please read https://support.twitter.com/articles/110250-adding-your-mobile-number-to-your-account-via-web for more information.

This may be good  to point out in the article so people don't start creating twitter accounts for this and then run into this problem in an Education Environment.
Like I have just done.
This is a Twitter problem, but renders the process unusable :-(

**Comment by lawsie** [comment]
I don't think it *always* requires a phone number for this - see #3. I'm not sure under what circumstances a phone number is or isn't required though!

**Comment by bsimmo** [comment]
Ask a few to create a new account with a new email address (or an already
in use one email *without* a phone number attached on any feed) and find
out if it requires a phone number.
See which comes up the most ;-).
No doubt the people seeing they don't need it may already have an account
with a phone number for another feed?
(UK here).

It stopped it in it's tracks here.
There is nothing you can do about it, but a warning for people was all I
was thinking.
